### ISSUE TITLE
Mobile friendly?

### ISSUE THREAD

**Issue by shiya** [Autodesk-Forge/autodesk-forge.github.io#5]
![img_6587](https://cloud.githubusercontent.com/assets/3713384/21298865/c735bbfa-c5d0-11e6-89ce-f8e471cc76d2.PNG)
This page is not responsive.. Do we need to make it mobile friendly too? Should one even be looking at code samples on a phone?

**Comment by leefsmp** [comment]
Ideally all our pages would need to be ...

**Comment by shiya** [comment]
github.com isn't responsive

**Comment by augustogoncalves** [comment]
I tested on my phone, it works fine (all links and filters). I agree is not mobile friendly...

**Comment by cyrillef** [comment]
Shiya, I am not sure I understand your logic, unless I am missing the point. github.com might not be responsive, that does not prevent you to be responsive ;)

**Comment by shiya** [comment]
All the links goes to github.com.

**Comment by leefsmp** [comment]
Isn't this page supposed to be a showcase of our samples and APIs rather than a list of links?

**Comment by shiya** [comment]
The samples are on Github therefore the links goes to GitHub. What other features would you like me to implement?

**Comment by cyrillef** [comment]
They will also go to live demos which are in theory responsive - anyway this is a moot point, make it responsive.
